version: "3.9"

services:
    php:
        container_name: php
        image: php
        restart: always
        command: bash -c "a2enmod rewrite && apache2-foreground"
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:80"
        environment: 
          - COMPOSER_ALLOW_SUPERUSER=1
        depends_on:
          - mysql
        volumes:
          - .:/var/www/html
    mysql:
      image: mysql:5.7
      restart: always
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_USER: user
          MYSQL_ROOT_PASSWORD: user
          MYSQL_DATABASE: db
    # node:
    #   image: node:18.15.0-alpine
    #   restart: always
    #   command: sh -c "cd /app && npm install && npm run watch"
    #   volumes:
    #       - ./front:/app
    #       - ./back:/app/xd
