name: Deploy BE
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy BE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
      - name: Dump autoload
        working-directory: ./back
        run: composer dump-autoload -o
      - name: Sync
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.epizy.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./back/
          server-dir: htdocs/
