name: Deploy FE
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy FE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install
        working-directory: ./front
        run: npm install
      - name: Build
        working-directory: ./front
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/build
          force_orphan: true
          publish_branch: pages
          cname: scandiweb.ukasz.com
